//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCrudSOAP.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPaciente", ReplyAction="*")]
        ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse AgregarPaciente(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse> AgregarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerPacientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPacientes", ReplyAction="*")]
        ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse ObtenerPacientes(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse> ObtenerPacientesAsync(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPaciente", ReplyAction="*")]
        ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse ActualizarPaciente(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse> ActualizarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EliminarPacienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPaciente", ReplyAction="*")]
        ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse EliminarPaciente(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse> EliminarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequestBody Body;
        
        public AgregarPacienteRequest() {
        }
        
        public AgregarPacienteRequest(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        public AgregarPacienteRequestBody() {
        }
        
        public AgregarPacienteRequestBody(string name, int age) {
            this.name = name;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponseBody Body;
        
        public AgregarPacienteResponse() {
        }
        
        public AgregarPacienteResponse(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarPacienteResult;
        
        public AgregarPacienteResponseBody() {
        }
        
        public AgregarPacienteResponseBody(string AgregarPacienteResult) {
            this.AgregarPacienteResult = AgregarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPacientes", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequestBody Body;
        
        public ObtenerPacientesRequest() {
        }
        
        public ObtenerPacientesRequest(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerPacientesRequestBody {
        
        public ObtenerPacientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponseBody Body;
        
        public ObtenerPacientesResponse() {
        }
        
        public ObtenerPacientesResponse(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.Paciente[] ObtenerPacientesResult;
        
        public ObtenerPacientesResponseBody() {
        }
        
        public ObtenerPacientesResponseBody(ConsoleCrudSOAP.ServiceReference1.Paciente[] ObtenerPacientesResult) {
            this.ObtenerPacientesResult = ObtenerPacientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequestBody Body;
        
        public ActualizarPacienteRequest() {
        }
        
        public ActualizarPacienteRequest(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        public ActualizarPacienteRequestBody() {
        }
        
        public ActualizarPacienteRequestBody(int id, string name, int age) {
            this.id = id;
            this.name = name;
            this.age = age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponseBody Body;
        
        public ActualizarPacienteResponse() {
        }
        
        public ActualizarPacienteResponse(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarPacienteResult;
        
        public ActualizarPacienteResponseBody() {
        }
        
        public ActualizarPacienteResponseBody(string ActualizarPacienteResult) {
            this.ActualizarPacienteResult = ActualizarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequestBody Body;
        
        public EliminarPacienteRequest() {
        }
        
        public EliminarPacienteRequest(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public EliminarPacienteRequestBody() {
        }
        
        public EliminarPacienteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponseBody Body;
        
        public EliminarPacienteResponse() {
        }
        
        public EliminarPacienteResponse(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarPacienteResult;
        
        public EliminarPacienteResponseBody() {
        }
        
        public EliminarPacienteResponseBody(string EliminarPacienteResult) {
            this.EliminarPacienteResult = EliminarPacienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ConsoleCrudSOAP.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleCrudSOAP.ServiceReference1.WebServiceSoap>, ConsoleCrudSOAP.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.AgregarPaciente(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest request) {
            return base.Channel.AgregarPaciente(request);
        }
        
        public string AgregarPaciente(string name, int age) {
            ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse retVal = ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).AgregarPaciente(inValue);
            return retVal.Body.AgregarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse> ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.AgregarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest request) {
            return base.Channel.AgregarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.AgregarPacienteResponse> AgregarPacienteAsync(string name, int age) {
            ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.AgregarPacienteRequestBody();
            inValue.Body.name = name;
            inValue.Body.age = age;
            return ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).AgregarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.ObtenerPacientes(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest request) {
            return base.Channel.ObtenerPacientes(request);
        }
        
        public ConsoleCrudSOAP.ServiceReference1.Paciente[] ObtenerPacientes() {
            ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest inValue = new ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequestBody();
            ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse retVal = ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).ObtenerPacientes(inValue);
            return retVal.Body.ObtenerPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse> ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.ObtenerPacientesAsync(ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest request) {
            return base.Channel.ObtenerPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesResponse> ObtenerPacientesAsync() {
            ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest inValue = new ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.ObtenerPacientesRequestBody();
            return ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).ObtenerPacientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.ActualizarPaciente(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest request) {
            return base.Channel.ActualizarPaciente(request);
        }
        
        public string ActualizarPaciente(int id, string name, int age) {
            ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.age = age;
            ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse retVal = ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).ActualizarPaciente(inValue);
            return retVal.Body.ActualizarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse> ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.ActualizarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest request) {
            return base.Channel.ActualizarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteResponse> ActualizarPacienteAsync(int id, string name, int age) {
            ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.ActualizarPacienteRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.age = age;
            return ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).ActualizarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.EliminarPaciente(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest request) {
            return base.Channel.EliminarPaciente(request);
        }
        
        public string EliminarPaciente(int id) {
            ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequestBody();
            inValue.Body.id = id;
            ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse retVal = ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).EliminarPaciente(inValue);
            return retVal.Body.EliminarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse> ConsoleCrudSOAP.ServiceReference1.WebServiceSoap.EliminarPacienteAsync(ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest request) {
            return base.Channel.EliminarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleCrudSOAP.ServiceReference1.EliminarPacienteResponse> EliminarPacienteAsync(int id) {
            ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest inValue = new ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequest();
            inValue.Body = new ConsoleCrudSOAP.ServiceReference1.EliminarPacienteRequestBody();
            inValue.Body.id = id;
            return ((ConsoleCrudSOAP.ServiceReference1.WebServiceSoap)(this)).EliminarPacienteAsync(inValue);
        }
    }
}
